image: ubuntu:focal

before_script:
  - ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone
  - apt-get update
  - apt-get install -y make qtbase5-dev-tools zip

stages:
  - build

package:
  stage: build
  script:
    - make
    - cp build/keyboard-mapper keyboard-mapper
  artifacts:
    paths:
      - keyboard-mapper
      - CHANGELOG.md
      - LICENSE
      - README.md
      - requirements.txt