name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y qtbase5-dev-tools
      - run: make package
      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          files: build/keyboard-mapper.zip